version: '2'
services:
  hadoop-dfs-namenode:
    build: ./hadoop-dfs-namenode
    hostname: hadoop-dfs-namenode
    ports:
      - 8020:8020
      - 50070:50070
  hadoop-dfs-datanode:
    build: ./hadoop-dfs-datanode
    hostname: hadoop-dfs-datanode
    depends_on:
      - hadoop-dfs-namenode
    ports:
      - 50010:50010
      - 50020:50020
      - 50075:50075
  hadoop-yarn-resourcemanager:
    build: ./hadoop-yarn-resourcemanager
    hostname: hadoop-yarn-resourcemanager
    ports:
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 8088:8088
      - 8090:8090
  hadoop-yarn-nodemanager:
    build: ./hadoop-yarn-nodemanager
    hostname: hadoop-yarn-nodemanager
    depends_on:
      - hadoop-yarn-resourcemanager
    ports:
      - 8040:8040